before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/
stages:
  - lints

runDetekt:
  image: martinsumera/gitlab-ci-android
  stage: lints
  only:
    - merge_requests
  script:
    - ./gradlew :detekt
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - build/reports/detekt/detekt.html
